---
- shell: mkdir -p {{ int_data }}
- name: Upload key material for integration tests
  copy: src=/var/data/sks-dump/{{ data_file }} dest={{ int_data }}/{{ data_file }} mode=644
- name: Stop Hockeypuck
  service: name=hockeypuck state=stopped
- name: Drop database constraints
  shell: su - hockeypuck -c 'hockeypuck db --config /etc/hockeypuck/hockeypuck.conf --drop-constraints'
- name: Load dump files
  shell: su - hockeypuck -c 'hockeypuck load --config /etc/hockeypuck/hockeypuck.conf --path {{int_data}}/*.pgp'
- name: Rebuild database constraints
  shell: su - hockeypuck -c 'hockeypuck db --config /etc/hockeypuck/hockeypuck.conf --dedup --create-constraints'
- name: Start Hockeypuck
  service: name=hockeypuck state=started
