name: hockeypuck
base: core18
version: '2.0.4'
summary: OpenPGP Public Keyserver
description: |
  Hockeypuck is an OpenPGP Key Server implementing the HTTP Keyserver Protocol.

grade: stable
confinement: strict

apps:
  hockeypuck:
    command: hockeypuck-wrapper
    daemon: simple
    plugs:
    - network
    - network-bind
    - removeable-media
    daemon: simple
  load:
    command: hockeypuck-load-wrapper
    plugs:
    - network
    - network-bind
    - removeable-media
  dump:
    command: hockeypuck-dump-wrapper
    plugs:
    - network
    - network-bind
    - removeable-media
  pbuild:
    command: hockeypuck-pbuild-wrapper
    plugs:
    - network
    - network-bind
    - removeable-media

parts:
  hockeypuck:
    build-packages:
    - build-essential
    - software-properties-common
    override-build: |-
      cp snap/local/*-wrapper $SNAPCRAFT_PART_INSTALL
      cp -r contrib/templates $SNAPCRAFT_PART_INSTALL
      cp -r contrib/webroot $SNAPCRAFT_PART_INSTALL
      sudo add-apt-repository -y ppa:canonical-sysadmins/golang
      sudo apt-get update
      make install-build-depends build
    plugin: nil
    source: .
